#! /bin/bash
# NAME labsis-cambio-password
#
#       per ogni classe in orario crea il file xml dal template

versione="1.0.0"

# USO:
# TODO: scrivere l'uso
echo "cambio password per  $USER "
passwd  $USER
exitcodepasswd=$?
echo $exitcodepasswd 

if [ $exitcodepasswd -ne 0 ]
then
  echo "qualcosa è andato storto nel cambio password"
  echo " il cambio ha prodotto l'exit code $exitcode-passwd"
  exit 1
else
  (echo -e "\n" ) | sudo /usr/lib/yp/ypinit -m
  exit 0
fi

