#!/bin/bash
# questa riga serve per definire quale interprete usare 

#todo: inserire controllo input parametri;

#sono due variabili che sono poste ai valori dei parametri di linea
GRUPPO=$1
FILE=$2
AS="2017.18"

#crea  il gruppo 
#TODO : inserire controllo
/usr/sbin/addgroup --force-badname $GRUPPO

#crea directory as/GRUPPO

mkdir -p /home/$AS/$GRUPPO



while read UTENTE  
do
	echo "****************************************"
	echo aggiungo lo user : $UTENTE
	echo "****************************************"
	
	# aggiunge l'utente
	/usr/sbin/adduser --force-badname --home /home/$UTENTE  --disabled-login --gecos $UTENTE  $UTENTE 
	
	# aggiunge l'utente al gruppo 
	/usr/sbin/adduser $UTENTE $GRUPPO
	
	#imposta la password iniziale
	echo "$UTENTE:koala" | chpasswd
	
	#rende privata la home directory 
	chmod o-rwx /home/$UTENTE
	
	#aggiunge l'utente paolo al gruppo dell'utente 
	/usr/sbin/adduser paolo $UTENTE
	
	#crea link in 
	
	ln -s /home/$UTENTE /home/$AS/$GRUPPO/$UTENTE
done < $FILE
